version: "3.8"

services:
  frontend:
    build: .
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/keeper

  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=keeper

